server {
    # コンテナ内のNginxは80番で待ち受ける
    listen 80;

    # 公開フォルダ
    # docker-compose.yml で ./wordpress を /var/www/html に見せている
    root /var/www/html/public;

    # 最初に探すファイル
    index index.php index.html;

    # 通常アクセス
    # ファイルがあれば返す
    # なければ index.php に渡す
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # .php にアクセスされた時の処理
    # Nginx自身はPHPを実行できないので、PHP-FPMへ渡す
    location ~ \.php$ {
        include fastcgi_params;

        # php は docker-compose.yml のサービス名
        # 9000 はPHP-FPMが待ち受ける標準ポート
        fastcgi_pass php:9000;

        # 実行するPHPファイルのパスをPHP-FPMへ伝える
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}